export const heroSectionSlider = [
    {
        id: 1,
        image: "/images/herosection9.webp",
    },
    {
        id: 2,
        image: "/images/herosection10.webp",
    },
    {
        id: 3,
        image: "/images/herosection11.webp",
    },
    {
        id: 4,
        image: "/images/herosection14.webp",
    },
    {
        id: 5,
        image: "/images/herosection7.webp",
    },
    {
        id: 6,
        image: "/images/herosection15.webp",
    },
    {
        id: 7,
        image: "/images/herosection13.webp",
    },
    {
        id: 8,
        image: "/images/herosection8.webp",
    },
];

export const editorPickProducts = [
    {
        id: 1,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/editors1.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 2,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/editors2.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 3,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/editors3.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 4,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/editors4.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 5,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/editors5.avif",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 0,
    },
    {
        id: 6,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/bestsellers6.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 7,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/bestsellers7.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 8,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/bestsellers8.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 9,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/bestsellers9.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 10,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/bestsellers10.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
];

export const budgetBeautyProducts = [
    {
        id: 1,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/budgetbeauty1.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 2,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/budgetbeauty2.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 3,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/budgetbeauty3.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 4,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/budgetbeauty4.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 5,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/budgetbeauty5.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 0,
    },
    {
        id: 6,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/bestsellers6.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 7,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/bestsellers7.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 8,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/bestsellers8.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 9,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/bestsellers9.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 10,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/bestsellers10.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
];

export const essentialProducts = [
    {
        id: 1,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/essentials1.avif",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 2,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/essentials2.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 3,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/essentials3.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 4,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/essentials4.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 5,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/essentials5.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 0,
    },
    {
        id: 6,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/bestsellers6.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 7,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/bestsellers7.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 8,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/bestsellers8.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 9,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/bestsellers9.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 10,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/bestsellers10.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
];

export const curatedProducts = [
    {
        id: 1,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/curated1.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 2,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/curated2.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 3,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/curated3.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 4,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/curated4.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 5,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/curated5.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 0,
    },
    {
        id: 6,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/bestsellers6.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 7,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/bestsellers7.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 8,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/bestsellers8.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 9,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/bestsellers9.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
    {
        id: 10,
        title: "Dove Daily Shine",
        subtitle: "Bio PRO Shampoo 340ml",
        image: "/images/bestsellers10.webp",
        price: 290,
        oldPrice: 435,
        discount: 33,
        offers: 3,
    },
];

export const getfreegifts = [
    {
        id: 1,
        image: "/images/freegifts1.webp",
    },
    {
        id: 2,
        image: "/images/freegifts2.webp",
    },
    {
        id: 3,
        image: "/images/freegifts3.webp",
    },
    {
        id: 4,
        image: "/images/freegifts4.webp",
    },
    {
        id: 5,
        image: "/images/freegifts5.webp",
    },
    {
        id: 6,
        image: "/images/freegifts6.webp",
    },
];

export const topBrands = [
    {
        id: 1,
        image: "/images/topbrands1.webp",
    },
    {
        id: 2,
        image: "/images/topbrands2.webp",
    },
    {
        id: 3,
        image: "/images/topbrands3.webp",
    },
    {
        id: 4,
        image: "/images/topbrands4.webp",
    },
    {
        id: 5,
        image: "/images/topbrands5.webp",
    },
    {
        id: 6,
        image: "/images/topbrands6.webp",
    },
    {
        id: 7,
        image: "/images/topbrands7.webp",
    },
    {
        id: 8,
        image: "/images/topbrands8.webp",
    },
    {
        id: 9,
        image: "/images/topbrands9.webp",
    },
    {
        id: 10,
        image: "/images/topbrands10.webp",
    },
    {
        id: 11,
        image: "/images/topbrands11.webp",
    },
    {
        id: 12,
        image: "/images/topbrands12.webp",
    },
];

export const magazineBlogs = [
    {
        id: 1,
        image: "/images/magazine-blogs1.webp",
    },
    {
        id: 2,
        image: "/images/magazine-blogs2.webp",
    },
    {
        id: 3,
        image: "/images/magazine-blogs3.webp",
    },
    {
        id: 4,
        image: "/images/magazine-blogs4.webp",
    },
    {
        id: 5,
        image: "/images/magazine-blogs5.webp",
    },
    {
        id: 6,
        image: "/images/magazine-blogs6.webp",
    },
    {
        id: 7,
        image: "/images/magazine-blogs7.webp",
    },
];

